apiVersion: batch/v1beta1
kind: CronJob
metadata:
  namespace: public-api
  name: zhihu-spider
  labels:
    app: zhihu-spider
spec:
  schedule: "0 1-23/2 * * *"
  successfulJobsHistoryLimit: 0
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: zhihu-spider
        spec:
          imagePullSecrets:
            - name: registry-secret
          containers:
            - name: zhihu-spider
              image: __IMAGE_FULL_NAME__
              imagePullPolicy: Always
              env:
              - name: APP_SENTRYDSN
                value: https://da71503fc8de4f41909fe1a3539ae53f@sentry.io/3831823
              - name: APP_DB_DBNAME
                value: ncovis
              - name: APP_DB_URI
                value: mongodb://mongodb:27017/
              - name: APP_NLP_ADDRESS
                value: nlp-api:12377
              - name: APP_SPIDER_DELAY
                value: "500"
              - name: APP_SPIDER_SORTBY
                value: default
              - name: APP_SPIDER_MAXTOPICS
                value: "10"
              - name: APP_SPIDER_MAXPAGES
                value: "20"
          restartPolicy: OnFailure
